default_yolo_source: 0
cam_id: uuid
cors:
  allowed_headers:
  - Content-Type
  allowed_methods:
  - GET
  - OPTIONS
  allowed_origins:
  - http://localhost:5173
counters:
  zone_counter:
    enabled: true
    zones:
    - color:
      - 0
      - 0
      - 200
      name: main
      points:
      - - 0
        - 0
      - - 100
        - 0
      - - 100
        - 100
      - - 0
        - 100
  crowd_counter:
    enabled: false
default_model: yoloe-11s-seg-custom.pt
default_server_port: 8000
access_key: 11111
secret_key: 11111
