# config.yaml
instances:
  - name: instance1
    camera: "~/Downloads/video.mp4"
    api_port: 8000
  # - name: instance1
  #   camera: 0
  #   api_port: 8000
  - name: instance2
    camera: "~/Downloads/video2.mp4"
    api_port: 8001

default_model: "yolov10n.pt"

# CORS settings
cors:
  allowed_origins:
    - "http://localhost:5173"
    # Add more origins as needed
  allowed_methods:
    - "GET"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
