default_yolo_source: "/tmp/webcam/"
cam_id: 22222222-2222-2222-2222-222222222222
cors:
  allowed_headers:
  - Content-Type
  allowed_methods:
  - GET
  - OPTIONS
  allowed_origins:
  - http://localhost:5173
counters:
  zone_counter:
    enabled: true
    zones:
    - color:
      - 0
      - 0
      - 200
      name: main
      points:
      - - 0
        - 0
      - - 100
        - 0
      - - 100
        - 100
      - - 0
        - 100
  crowd_counter:
    enabled: false
default_model: yolo11n.pt
default_server_port: 8000
access_key: staging_key
secret_key: staging_secret