# config.yaml
default_camera: 0
default_model: "yolov10n.pt"
default_server_port: 8000

default_classes:
  - 0

# CORS settings
cors:
  allowed_origins:
    - "http://localhost:5173"
    # Add more origins as needed
  allowed_methods:
    - "GET"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
