default_yolo_source: 0
cam_id: 2efdad08-2da0-44bd-8b62-29009bc25389
cors:
  allowed_headers:
  - Content-Type
  allowed_methods:
  - GET
  - OPTIONS
  allowed_origins:
  - http://localhost:5173
counters:
  zone_counter:
    zones:
    - color:
      - 0
      - 0
      - 200
      name: principal
      points:
      - - 0
        - 0
      - - 100
        - 0
      - - 100
        - 100
      - - 0
        - 100
    - color:
      - 200
      - 200
      - 200
      name: out_top_left
      points:
      - - 7
        - 46
      - - 17.24
        - 45.27
      - - 18
        - 61
      - - 6
        - 73
    - color:
      - 200
      - 200
      - 200
      name: out_door_left
      points:
      - - 26
        - 53
      - - 38
        - 56
      - - 37
        - 67
      - - 26
        - 66
    - color:
      - 200
      - 200
      - 200
      name: out_door_right
      points:
      - - 48
        - 58
      - - 60
        - 60
      - - 60
        - 70
      - - 48
        - 68
    - color:
      - 200
      - 200
      - 200
      name: out_bottom_right
      points:
      - - 95
        - 76
      - - 92
        - 98
      - - 99
        - 99
      - - 100
        - 76
    - color:
      - 200
      - 200
      - 200
      name: out_bottom
      points:
      - - 0
        - 71
      - - 4
        - 71
      - - 5
        - 94
      - - 92
        - 94
      - - 92
        - 100
      - - 0
        - 100
default_model: yolo12s.pt
default_server_port: 8000
