[cameras]
cam_001 ansible_host=f1-ca-001 ansible_user=admin
cam_002 ansible_host=f1-ca-002 ansible_user=admin
cam_003 ansible_host=f1-ca-003 ansible_user=admin
cam_004 ansible_host=f1-ca-004 ansible_user=admin
cam_005 ansible_host=f1-ca-005 ansible_user=admin
cam_007 ansible_host=f1-ca-007 ansible_user=admin
cam_009 ansible_host=f1-ca-009 ansible_user=admin
cam_011 ansible_host=f1-ca-011 ansible_user=admin
cam_012 ansible_host=f1-ca-012 ansible_user=admin
cam_013 ansible_host=f1-ca-013 ansible_user=admin
cam_014 ansible_host=f1-ca-014 ansible_user=admin
cam_015 ansible_host=f1-ca-015 ansible_user=admin
cam_016 ansible_host=f1-ca-016 ansible_user=admin
cam_017 ansible_host=f1-ca-017 ansible_user=admin
dev_cam_010 ansible_host=f1-ca-010 ansible_user=admin

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/Users/admin/.pyenv/shims/python
