#!/usr/bin/env bash

# Fail immediately if a command has non-zero exit code
set -e

PERMANENT_PROFILE='permanent'
DEFAULT_PROFILE='default'

# Check if the "permanent" configuration exists in ~/.aws/credentials
if [[ $(aws configure --profile "$PERMANENT_PROFILE" list 2>&1) && $? -eq 0 ]]; then
    # Do nothing, because permanent is already set up
    true
else
    echo 'Renaming current default keys to "permanent"'
    # Create the permanent configuration
    AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile "$DEFAULT_PROFILE")
    AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile "$DEFAULT_PROFILE")
    aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile "$PERMANENT_PROFILE"
    aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile "$PERMANENT_PROFILE"
fi

MFA_SERIAL=$(aws configure get mfa_serial --profile "$DEFAULT_PROFILE" || printf '')
if [[ -z "$MFA_SERIAL" ]]; then
    ACCOUNT=128868293117
    read -p "Enter your AWS username: " GIVEN_AWS_USERNAME
    ARN="arn:aws:iam::${ACCOUNT}:mfa/${GIVEN_AWS_USERNAME}"
    aws configure set mfa_serial $ARN --profile "$DEFAULT_PROFILE"
fi

DURATION=$(aws configure get get_session_token_duration_seconds --profile "$DEFAULT_PROFILE" || printf '')
if [[ -z "$DURATION" ]]; then
    # 20 hours
    aws configure set get_session_token_duration_seconds "72000" --profile "$DEFAULT_PROFILE"
fi

# Setting up git configuration
if [[ -z $(git config --local credential.helper 2>/dev/null ) ]]; then
    echo 'Updating git configuration. NOTE: MFA is only available with https. Changing local git config to use that.'
    if [[ $(uname -s) = 'Darwin' ]]; then
        sed -i '' 's,url = ssh://,url = https://,' .git/config
    else
        sed -i 's,url = ssh://,url = https://,' .git/config
    fi
    git config --local credential.helper ''
    git config --local --add credential.helper '!aws codecommit --profile default credential-helper $@'
    git config --local credential.UseHttpPath true
fi
"$(git rev-parse --show-toplevel)/setup-scripts/refresh-mfa"
